# -*- coding: utf-8 -*-
"""GovernmentAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AC2pyk77GBE2HpYbDUGbxCMf5ciMDmfg
"""

import requests
from pprint import pprint
import matplotlib.pyplot as plt


def SearchProject(keyword_search='เรือดำน้ำ',year=2562,limit=20):

  url = 'https://opend.data.go.th/govspending/cgdcontract'

  token = 'NASRlMcRmDKjSjb8O9fsFF5B5QvB3Yll'

  parameters = {'api-key':token,
                'year':2562,
                'keyword':keyword_search,
                'limit':limit
                }


  r = requests.get(url,params=parameters)

  result = r.json()

  allproject = result['result']
  # print(type(allproject))
  print('Count: ',len(allproject)) #len() การนับค่าใน List/Dict
  # pprint(allproject[8])
  
  allbudget = []
  projectname = []




  print('---------parameter---------')
  print(allproject[0].keys())
  print('---------------------------')
  for pj in allproject:
    print(pj['dept_name'])
    print(pj['sum_price_agree'])
    print(pj['project_name'])
    print(pj['transaction_date'])
    allbudget.append(int(pj['sum_price_agree'].replace(',','')))
    projectname.append(pj['project_name'])
    print('---------------')
  print('***************************************************')

  print('ค้นหาคำว่า: {} งบประมาณทั้งหมด: {:,d} บาท'.format(keyword_search,sum(allbudget)))

  print('***************************************************')

  #graph
  # xbar= range(len(projectname))
  # plt.bar(xbar,allbudget)
  # plt.xticks(projectname)
  # plt.show()

SearchProject('หน้ากากอนามัย',2562)